#!/usr/bin/env python

import os
import sqlite3


conn = sqlite3.connect('rucv.db')
cursor = conn.cursor()
clips_dir = 'corpus/clips/'


os.chdir(clips_dir)

cursor.execute('SELECT original_filename, new_filename FROM sentence WHERE new_filename IS NOT NULL')
for sentence in cursor:
    original, new = sentence
    if os.path.isfile(original):
        os.rename(original, new)

    print(new)
