#!/usr/bin/env python

import json
import sqlite3


SENTENCES_PER_PAGE=50

conn = sqlite3.connect('rucv.db')
sentence_cursor = conn.cursor()
crc_cursor = conn.cursor()

page_count = 0
sentence_count = 0
page = []

def save_page(page, data):
    with open(f'/tmp/rucv/{page}.json', 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False)


crc_cursor.execute('SELECT DISTINCT(crc) FROM sentence WHERE selected > 0 AND score > 1 ORDER BY score ASC')
for crc in crc_cursor:
    sentence = {}
    sentences = sentence_cursor.execute('SELECT content, gender, filename, selected FROM sentence INNER JOIN speaker ON sentence.speaker = speaker.id WHERE selected > 0 AND crc = ? ORDER BY selected ASC', (crc[0],)).fetchall()

    speakers = []
    for s in sentences:
        speaker = {}
        speaker['gender'] = s[1] or 'unknown'
        speaker['filename'] = s[2]
        sentence['text'] = s[0]

        speakers.append(speaker)

    sentence['speakers'] = speakers

    page.append(sentence)
    sentence_count += 1

    if len(page) == SENTENCES_PER_PAGE:
        page_count += 1
        save_page(page_count, { 'sentences': page })
        page.clear()

page_count += 1
if page:
    save_page(page_count, { 'sentences': page })

for page in range(1, page_count + 1):
    with open(f'/tmp/rucv/{page}.json', 'r', encoding='utf-8') as f:
        data = json.load(f)

    data['meta'] = {
        'totalSentences': sentence_count,
        'totalPages': page_count
    }

    save_page(page, data)
