#!/usr/bin/env python

import sqlite3


conn = sqlite3.connect('rucv.db')
server_conn = sqlite3.connect('server/rucv.db')
cursor = conn.cursor()
server_cursor = server_conn.cursor()


cursor.execute('SELECT id, gender FROM speaker')
for speaker in cursor:
    id_, gender = speaker
    server_cursor.execute('INSERT OR IGNORE INTO speaker VALUES (?, ?)', (id_, gender))

server_conn.commit()

cursor.execute('SELECT id, content, score, new_filename, speaker FROM sentence WHERE selected > 0 AND score > 1 ORDER BY score ASC')
for sentence in cursor:
    id_, content, score, filename, speaker = sentence
    server_cursor.execute('INSERT INTO sentence VALUES (?, ?, ?, ?, ?)', (id_, content, filename, score, speaker))

server_conn.commit()
