#!/usr/bin/env python

import sqlite3


conn = sqlite3.connect('rucv.db')
update_cursor = conn.cursor()
sentence_cursor = conn.cursor()

update_cursor.execute('UPDATE speaker SET (total_upvotes, total_downvotes) = (0, 0)')
conn.commit()

sentence_cursor.execute('SELECT speaker, upvotes, downvotes FROM sentence')
for row in sentence_cursor:
    speaker, upvotes, downvotes = row
    update_cursor.execute(
        'UPDATE speaker '
        'SET '
          'total_upvotes = total_upvotes + ?, '
          'total_downvotes = total_downvotes + ? '
        'WHERE id = ?',
        (upvotes, downvotes, speaker)
    )

conn.commit()
